language: c
sudo: required
os: linux
dist: trusty

script:
  - bash -ex build.sh
  - bash -ex build-appimage.sh
  - curl --upload-file ./*.AppImage https://transfer.sh/appimagetool

notifications:
  irc:
    channels: 
      - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
