language: c
compiler: gcc

services:
  - docker
 
env:
# - DOCKER_IMAGE=toopher/centos-i386:centos6 # Pull request welcome that makes this work
  - DOCKER_IMAGE=library/centos:6.8
 
script:
  - mkdir -p ./out/
  - docker run -i -v ${PWD}/out:/out -v "${PWD}:/AppImageKit" "$DOCKER_IMAGE" /bin/bash -c "cd /AppImageKit ; yum -y install sudo ; sudo ./build.sh"

after_success:
  - ls -lh out/*
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - rm -rf out/appimaged out/appimagetool || true # We have AppImages for these
  - rm -rf out/runtime || true # Not needed, might confuse users
  - bash ./upload.sh out/*

notifications:
  irc:
    channels: 
      - "chat.freenode.net#AppImage"
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
    template:
      - "%{repository} build %{build_number}: %{result} %{build_url}"
    use_notice: true
    # skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4bf20518805a55998cc2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always

branches:
  except:
  - # Do not build tags that we create when we upload to GitHub Releases
  - /^(?i:continuous)$/

secure: "mxQFPlyUZsvP4OucRMDM1e3YjTsFQP5/e81FMIjCDgqlcoqMtIlEPNgGeK0MJbw1aciQuTfKz79wA9WyaDyvigEnkAXNviNXhL15jW2HWfinWr5P4/ubeWa9VpyJtLNhkPUO0l8314GJiuG6KB+V5lB9djQ6xxwHTrfQUfWvaaY=" # $KEY
