language: c
compiler: gcc
dist: trusty

before_install:
 - sudo apt-add-repository -y ppa:vala-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfuse-dev libglib2.0-dev cmake libc6-dev binutils valac libgee-0.8-dev gcc-multilib g++-multilib libc6-dev-i386

script: 
 - cmake . && make
 - find . -type f

before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: Rtz7d+BKUnBT8D5FoE4XXCvVhRSQVdGK/c5VpI6IYuGhwmtx4RIvK78cICFPZq8k1xJm8yOuCOChX6EyElhUkYh5iPzDI/J7IiqBl+z+/V3aXx6W2PKyYLohZW3z9iomQbX2LQ6vHcZsNqQsjKZ2dW7Ja5Q9cZTFKiokMXsAERo=
  skip_cleanup: true
  file_glob: true
  file: 
   - ./AppImageExtract
   - ./AppRun
   - ./AppImageAssistant
   - ./AppImageMonitor
  on:
    tags: true
    all_branches: true
