language: c
compiler: gcc

services:
 - docker
 
env:
# - DOCKER_IMAGE=toopher/centos-i386:centos6 # Pull request welcome that makes this work
 - DOCKER_IMAGE=library/centos:6.8
 
script:
 - docker run -i -v "${PWD}:/AppImageKit" "$DOCKER_IMAGE" /bin/bash -c "cd /AppImageKit ; yum -y install sudo ; sudo ./build.sh"

after_success:
- file out/*
