language: c
compiler: clang

before_install:
 - sudo apt-add-repository ppa:vala-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfuse-dev libglib2.0-dev cmake git libc6-dev binutils valac libgee-dev-0.8
 - valac --pkg gee-0.8 --pkg posix --pkg glib-2.0 --pkg gio-2.0 ./LibcWrapGenerator/LibcWrapGenerator.vala
 - sudo ./LibcWrapGenerator --target 2.7 --libdir /lib --output libcwrap.h
 - find .
 
script: cmake . && make
