language: c
compiler: gcc

before_install:
 - sudo apt-add-repository -y ppa:vala-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfuse-dev libglib2.0-dev cmake git libc6-dev binutils valac libgee-0.8-dev
 - cd ./LibcWrapGenerator
 - valac --pkg gee-0.8 --pkg posix --pkg glib-2.0 --pkg gio-2.0 ./LibcWrapGenerator.vala
 - sudo ./LibcWrapGenerator --target 2.7 --libdir /lib --output libcwrap.h
 - sudo cp ./libcwrap.h /usr/include/
 - cd -

script: 
 - export CC='gcc -U_FORTIFY_SOURCE -include /usr/include/libcwrap.h'
 - cmake . && make
 - find . -type f

before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: jJBKTduvxWOc+0ANQJ3o+j+Pb71S2k2BbqqhyYvWZM40H8jW4euy4/NaLWYf5oNnF5YslmUtvK53m98sBpvu63sHNQ3vK/aoZEGMozFne76Z+PkgL3SZCr8ia/Un+IwEQ0C50FPGBa/osy583r2ajca0rKLlTN0M8zCTACCKm3w=
  skip_cleanup: true
  file_glob: true
  file: 
   - ./AppImageExtract
   - ./AppRun
   - ./AppImageAssistant
  on:
    tags: true
    all_branches: true
