language: c
compiler: clang

before_install:
 - depmod
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfuse-dev libglib2.0-dev cmake git libc6-dev binutils fuse
 - sudo mknod /dev/fuse c 10 229
 - modprobe fuse
 
script: cmake . && make
