language: c
compiler: clang

before_install:
 - modprobe fuse
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfuse-dev libglib2.0-dev cmake git libc6-dev binutils fuse

script: cmake . && make
